---
- id: go-fmt
  name: 'go fmt'
  entry: ./hooks/go-fmt.sh
  files: '\.go$'
  language: 'script'
- id: go-imports
  name: 'go imports'
  entry: ./hooks/go-imports.sh
  files: '\.go$'
  language: 'script'
