---
- id: cargo-check
  name: 'cargo check'
  entry: ./hooks/cargo-check.sh
  files: '^Cargo'
  language: 'script'
- id: go-build
  name: 'go build'
  entry: ./hooks/go-build.sh
  files: '\.go$'
  language: 'script'
- id: go-fmt
  name: 'go fmt'
  entry: ./hooks/go-fmt.sh
  files: '\.go$'
  language: 'script'
- id: go-imports
  name: 'go imports'
  entry: ./hooks/go-imports.sh
  files: '\.go$'
  language: 'script'
- id: go-mod-tidy
  name: 'go mod tidy'
  entry: ./hooks/go-mod-tidy.sh
  files: '\.mod'
  language: 'script'
- id: go-unit-tests
  name: 'go unit tests'
  entry: ./hooks/go-unit-tests.sh
  files: '\.go$'
  language: 'script'
- id: go-vet
  name: 'go vet'
  entry: ./hooks/go-vet.sh
  files: '\.go$'
  language: 'script'
- id: golangci-lint
  name: 'golangci lint'
  entry: ./hooks/golangci-lint.sh
  files: '\.go$'
  language: 'script'
- id: rust-fmt
  name: 'rust fmt'
  entry: ./hooks/rust-fmt.sh
  files: '\.rs$'
  language: 'script'
