---
- id: go-fmt
  name: 'go fmt'
  entry: ./hooks/go-fmt.sh
  files: '\.go$'
  language: 'script'
- id: go-imports
  name: 'go imports'
  entry: ./hooks/go-imports.sh
  files: '\.go$'
  language: 'script'
- id: go-unit-tests
  name: 'go unit tests'
  entry: ./hooks/go-unit-tests.sh
  files: '\.go$'
  language: 'script'
- id: go-vet
  name: 'go vet'
  entry: ./hooks/go-vet.sh
  files: '\.go$'
  language: 'script'
- id: golangci-lint
  name: 'golangci lint'
  entry: ./hooks/golangci-lint.sh
  files: '\.go$'
  language: 'script'
